name: React Native CI/CD

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main

jobs:
  ios-build:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install CocoaPods
        run: |
          cd ios
          bundle install
          bundle exec pod install

      - name: Build iOS bundle
        run: yarn run package-ios

      - name: Run Fastlane for iOS
        run: |
          cd ios
          bundle exec fastlane build_testflight

  android-build:
    name: Android Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Android bundle
        run: yarn run package-android

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Run Fastlane for Android
        run: |
          cd android
          bundle exec fastlane build_qa
