name: React Native CI/CD

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main

jobs:
  # ios-build:
  #   name: iOS Build
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Install Yarn
  #       run: npm install -g yarn
  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Setup Ruby and Bundler
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true

  #     - name: Install CocoaPods
  #       run: |
  #         cd ios
  #         bundle install
  #         bundle exec pod install

  #     - name: Build iOS bundle
  #       run: yarn run package-ios

  #     - name: Run Fastlane for iOS
  #       run: |
  #         cd ios
  # bundle exec fastlane build_testflight

  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      # - name: Run Tests
      #   run: yarn test --ci

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Clear Gradle cache
        run: rm -rf ~/.gradle/caches/

      - name: Create assets directory
        run: mkdir -p android/app/src/main/assets

      - name: Bundle JavaScript and Assets
        run: |
          npx react-native bundle --platform android --dev false --entry-file app/(tabs)/index.tsx --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew assembleRelease --stacktrace --info

      # - name: Run Fastlane for Android
      #   run: |
      #     cd android
      #     bundle exec fastlane build_qa
      # - name: Build Android bundle
      #   run: cd android && ./gradlew assembleRelease

      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2

      # - name: Execute Gradle build
      #   run: |
      #     cd android
      #     ./gradlew assembleRelease --stacktrace --info

      # - name: Run Fastlane for Android
      #   run: |
      #     cd android
      #     bundle exec fastlane build_qa
